### ISSUE TITLE
Benchmarks should avoid intermediate storage

### ISSUE THREAD

**Issue by tcbrindle** [serpent7776/cpp-ranges-bench#2]
The intro to the blog post notes that `filter -> reverse` is a tricky combination for ranges libraries. Because of this, most of the benchmarks save the results of the filter into a temporary vector and then reverse that.

However, the C like benchmark says that it "collects the result in a vector and when it's done, it reverses it in-place".

But we can of course do the equivalent -- collect in forward order, then reverse in-place at the end -- for other libraries too, so that they can also avoid any intermediate storage. For example, changing the Flux code to:

```cpp
std::vector<Out> fluxranges(const std::vector<Data>& v, std::predicate<Data> auto accept, size_t max_items)
{
    auto found = flux::zip(flux::ints(), flux::ref(v).filter(accept).take(max_items))
                    .map([](const auto& it){
                        return Out{.n=uint64_t(std::get<0>(it)), .id=std::get<1>(it).id, .name=std::get<1>(it).name};
                    })
                    .template to<std::vector>();
    flux::inplace_reverse(found);
    return found;
}
```

results in a much fairer comparison, as the solutions are now doing the same amount of work. Equivalent changes can be made for the std ranges and range-v3 functions as well, and all result in speedups for most of the tests.

**Comment by serpent7776** [comment]
I tried that version but it made a change only in the case of 'every other item' test. `flux ranges` is the current version, `flux ranges2` is suggested new version.

Maybe I'll just note that the reason why I wrote the code the way I did is because I tried to do what I though was idiomatic code for given library. I specifically did not try to optimise any implementation. When doing ranges version `v | reverse` felt more idiomatic. The C version came last and the only possibility I had was doing reverse in place. And after that I never came back to revisit other versions. So it's kinda that C forced me into doing more performant version. But maybe it's just my lack of experience with range libraries. Maybe I got distracted too much by libraries themselves.

Anyway, here are the results:

![all_ismiths](https://github.com/serpent7776/cpp-ranges-bench/assets/3284364/b464c5af-ac65-4b29-88d7-9ef43ec6169c)
![5_ismiths](https://github.com/serpent7776/cpp-ranges-bench/assets/3284364/6ec1c5b3-058d-4d18-b4b4-1b8ee0e93190)
![empty_result_set](https://github.com/serpent7776/cpp-ranges-bench/assets/3284364/d6b6ff77-c3f8-43ec-8f96-542c5df994a5)
![early_single_item](https://github.com/serpent7776/cpp-ranges-bench/assets/3284364/9c97eca7-c1f6-4aa2-9bbd-a1f0e4ddbcd4)
![late_single_item](https://github.com/serpent7776/cpp-ranges-bench/assets/3284364/0147b244-14f1-4ef5-a50a-f63b1fd8e334)
![every_other_item](https://github.com/serpent7776/cpp-ranges-bench/assets/3284364/4c43174a-6f7f-4d57-b4fc-2d220da724eb)

**Comment by tcbrindle** [comment]
Interesting, I expected it to show more of a difference but I guess not! 🤷🏻‍♂️

Thanks for trying it out anyway :)

**Comment by serpent7776** [comment]
Also tried it for std::ranges and ranges-v3 and results were similar. Just a guess, but I think that the cost of calling lambda overtook any cost of allocation.

**Comment by serpent7776** [comment]
I've removed extra allocation from ranges libraries except for boost adaptors and custom algorithms and updated the blog post.
